### ISSUE TITLE
How to auto populate Title and Description fields

### ISSUE THREAD

**Issue by vertesy** [yonicd/sinew#70]
Hello,

is there a way to auto populate Title and Description fields? 

I earlier wrote a much simpler package ([RoxygenReady](https://vertesy.github.io/RoxygenReady/)) for the same goal. I now discovered sinew, which works very nicely in general, but I did not find a features to auto populate `@title` and `@description` fields. Is it possible?

RoxygenReady copies to @description from the first comment within the function code, and copies too @title the name of the function. I am now trying to build [CodeAndRoll2](https://github.com/vertesy/CodeAndRoll2/blob/main/CodeAndRoll2.R) and would take a lot of manual copying. At least for @title,  it would arguably be a better default behavior. Sorry if I overlooked something.

**Comment by yonicd** [comment]
Thanks for trying out the package.

`title` and `description` are populated with templates that the user changes once they are initialized. 

The templates are hard coded into [makeOxygen](https://github.com/yonicd/sinew/blob/master/R/makeOxygen.R#L68_L70). 

I am open to changing it is you think that is something that would streamline making documentation.

The places you could PR into is adding the fields into [sinew_opts](https://github.com/yonicd/sinew/blob/master/R/opts.R#L76) and have the field contain a function that takes the name of the function being populated.

The description i think should stay the same as it is, but can also be moved to sinew_opts for uniformity. 

Hope that answers your questions.

**Comment by vertesy** [comment]
Thanks for getting back quickly!

1.  For @title, I think the function name is more informative as a default than _hard-coded standard text X_.
2. For @description, I understand that you cannot expect the first comment to be informative / be there in general. Would be a nice option though. 

Not sure what I should add to sinew_opts to achieve:
> copiy to @description from the first comment within the function code

**Comment by yonicd** [comment]
Description does get populated automatically, do you want control if that initial text?

**Comment by vertesy** [comment]
Yes indeed, I would like to dynamically parse it from the function body itself in both cases.

**Comment by yonicd** [comment]
I’m still confused regarding the description tag. Parse what from the function?

**Comment by vertesy** [comment]
Hey, I am so sorry that I wasn't clear!

I hope this example explains it better:

### Before

```r
 		print11more <- function(n=1, m=1) { # a function with real added value
			print (n+(11*m))
		}
```


### After
(Focus only on title and description)

```r
		#' @title print11more
		#'
		#' @description a function with real added value
		#' @param n
		#' @param m
		#' @examples print11more(n=1, m=1)
		#' @export


		print11more <- function(n=1, m=1) {
			print (n+(11*m))
		}
```

**Comment by yonicd** [comment]
I see now. Thanks for the explanation.

That description assumes behavior by the user. That unfortunately departs from how sinew is designed to not force the user to set up the input function in order for the skeleton to work.

I think though the title tag population could be a useful addition.
