### ISSUE TITLE
Consider incorporating clipr for easy copying of skeleton code

### ISSUE THREAD

**Issue by parmsam** [yonicd/sinew#74]
Could be added as T/F argument into makeOxygen for example
https://github.com/mdlincoln/clipr

**Comment by elipousson** [comment]
@parmsam It has been a while since you opened this but this is now an option for `makeOxygen()`. It defaults to `TRUE` if the session is interactive https://github.com/yonicd/sinew/pull/79

**Comment by yonicd** [comment]
closed by #79
